apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: homelab
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      nodePort: 30096    # Tailscale access: http://<worker-2-tailscale-ip>:30096
  type: NodePort
