apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    type: local
    storage-type: media
spec:
  storageClassName: local-media
  capacity:
    storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/media/jellyfin
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-type
              operator: In
              values:
                - media
