---
- name: Install ArgoCD
  hosts: k3s_master
  become: true
  roles:
    - argocd

- name: Reload AdGuard with ArgoCD DNS entry
  hosts: adguard_hosts
  become: true
  roles:
    - adguard
